export const trails = [
  {
    slug: "khumbu-odyssey",
    title: "The Khumbu Odyssey",
    altitude: "5,364m",
    distance: "130km",
    duration: "9 Days",
    detailDuration: "14 days",
    image: "/trail2.png",
    difficulty: "Hard",
    badge: "bg-[#b84d54]",
    text: "A technical high-altitude trek navigating the Khumbu Glacier. Requires acclimatization and stamina.",
    waypoints: [
      {
        day: "Day 1",
        title: "Lukla",
        altitude: "2,860m",
        text: "Start of the journey with a dramatic mountain landing and first steps into the Khumbu region.",
      },
      {
        day: "Day 3",
        title: "Namche Bazaar",
        altitude: "3,440m",
        text: "The Sherpa capital and the first major acclimatization stop.",
      },
      {
        day: "Day 6",
        title: "Dingboche",
        altitude: "4,410m",
        text: "A wide alpine valley used for rest before moving toward glacier terrain.",
      },
      {
        day: "Day 9",
        title: "Khumbu Glacier",
        altitude: "5,364m",
        text: "Glacial landscapes, rugged moraine paths, and the final high-altitude objective.",
      },
    ],
  },
  {
    slug: "thorong-la-pass",
    title: "Thorong La Pass",
    altitude: "5,416m",
    distance: "96km",
    duration: "6 Days",
    detailDuration: "12 days",
    image: "/trail3.png",
    difficulty: "Mod",
    badge: "bg-[#d9a528]",
    text: "A diverse cultural journey crossing one of the highest navigable mountain passes in the world.",
    waypoints: [
      {
        day: "Day 1",
        title: "Chame",
        altitude: "2,670m",
        text: "Begin through pine forests and traditional villages along the Annapurna Circuit.",
      },
      {
        day: "Day 3",
        title: "Manang",
        altitude: "3,540m",
        text: "A key acclimatization village surrounded by dry alpine landscapes.",
      },
      {
        day: "Day 5",
        title: "High Camp",
        altitude: "4,880m",
        text: "Final overnight stop before the pass crossing.",
      },
      {
        day: "Day 6",
        title: "Thorong La",
        altitude: "5,416m",
        text: "Cross the famous pass with sweeping views across Annapurna and Mustang.",
      },
    ],
  },
  {
    slug: "langtang-valley",
    title: "Langtang Valley",
    altitude: "3,870m",
    distance: "77km",
    duration: "7 Days",
    detailDuration: "8 days",
    image: "/trail4.png",
    difficulty: "Easy",
    badge: "bg-[#52a36d]",
    text: "A scenic valley trek through rhododendron forests ending at the spectacular Kyanjin Gompa.",
    waypoints: [
      {
        day: "Day 1",
        title: "Syabrubesi",
        altitude: "1,550m",
        text: "Trailhead village and gateway to the Langtang region.",
      },
      {
        day: "Day 3",
        title: "Langtang Village",
        altitude: "3,430m",
        text: "A rebuilt mountain settlement with Tamang culture and valley views.",
      },
      {
        day: "Day 5",
        title: "Kyanjin Gompa",
        altitude: "3,870m",
        text: "A peaceful monastery village surrounded by glaciers and peaks.",
      },
      {
        day: "Day 6",
        title: "Kyanjin Ri",
        altitude: "4,773m",
        text: "Optional viewpoint climb for panoramic Langtang Himal scenery.",
      },
    ],
  },
  {
    slug: "everest-base-camp",
    title: "Everest Base Camp",
    altitude: "8,848m",
    distance: "130km",
    duration: "8 Days",
    detailDuration: "14 days",
    image: "/trails5.png",
    difficulty: "Hard",
    badge: "bg-[#b84d54]",
    text: "The ultimate journey to the foot of the world's highest peak.",
    waypoints: [
      {
        day: "Day 1",
        title: "Lukla",
        altitude: "2,860m",
        text: "Fly into the mountains and begin the classic Everest trail.",
      },
      {
        day: "Day 4",
        title: "Namche Bazaar",
        altitude: "3,440m",
        text: "Acclimatize in the main trading hub of the Khumbu.",
      },
      {
        day: "Day 7",
        title: "Lobuche",
        altitude: "4,940m",
        text: "Move into colder alpine terrain close to the glacier.",
      },
      {
        day: "Day 9",
        title: "Everest Base Camp",
        altitude: "5,364m",
        text: "Reach the legendary base camp below the world's highest mountain.",
      },
    ],
  },
  {
    slug: "annapurna-base-camp",
    title: "Annapurna Base Camp",
    altitude: "4,130m",
    distance: "115km",
    duration: "5 Days",
    detailDuration: "10 days",
    image: "/trail6.png",
    difficulty: "Mod",
    badge: "bg-[#d9a528]",
    text: "A diverse cultural journey crossing one of the highest navigable mountain passes in the world.",
    waypoints: [
      {
        day: "Day 1",
        title: "Ghandruk",
        altitude: "1,940m",
        text: "A Gurung village with stone paths, local culture, and mountain views.",
      },
      {
        day: "Day 3",
        title: "Chhomrong",
        altitude: "2,170m",
        text: "Gateway village leading deeper into the Annapurna Sanctuary.",
      },
      {
        day: "Day 5",
        title: "Machapuchare Base Camp",
        altitude: "3,700m",
        text: "A dramatic stop below the sacred fishtail mountain.",
      },
      {
        day: "Day 6",
        title: "Annapurna Base Camp",
        altitude: "4,130m",
        text: "Reach the natural amphitheater surrounded by Annapurna peaks.",
      },
    ],
  },
  {
    slug: "gokyo-lakes",
    title: "Gokyo Lakes",
    altitude: "4,790m",
    distance: "92km",
    duration: "5 Days",
    detailDuration: "11 days",
    image: "/trail7.png",
    difficulty: "Easy",
    badge: "bg-[#52a36d]",
    text: "A scenic valley trek through rhododendron forests ending at the spectacular Kyanjin Gompa.",
    waypoints: [
      {
        day: "Day 1",
        title: "Dole",
        altitude: "4,200m",
        text: "Climb through quieter yak pasture trails away from the main Everest route.",
      },
      {
        day: "Day 3",
        title: "Machhermo",
        altitude: "4,470m",
        text: "A small highland village used for acclimatization before Gokyo.",
      },
      {
        day: "Day 5",
        title: "Gokyo Lakes",
        altitude: "4,790m",
        text: "Arrive beside turquoise alpine lakes surrounded by snowy peaks.",
      },
      {
        day: "Day 6",
        title: "Gokyo Ri",
        altitude: "5,357m",
        text: "Optional viewpoint with one of the widest panoramas in the Everest region.",
      },
    ],
  },
];

export const itineraryDays = [
  {
    day: 1,
    title: "Lukla -> Phakding",
    meta: "3.5 hrs - 8.2 km - +200m gain",
    text: "The journey begins with a scenic flight to Lukla followed by an easy descent into the Dudh Koshi valley.",
    lodge: "Yeti Mountain Home",
    price: "NPR 4,500 / night",
    image: "/stay1.png",
  },
  {
    day: 2,
    title: "Phakding -> Namche Bazaar",
    meta: "6.5 hrs - 10.5 km - +800m gain",
    text: "A challenging ascent through pine forests, crossing several suspension bridges before arriving at the Sherpa capital.",
    lodge: "Select Lodge for Namche Bazaar",
  },
  {
    day: 3,
    title: "Acclimatization in Namche",
    meta: "Critical Rest Day - +0m gain",
    text: "Rest, hydrate, and explore Namche Bazaar before climbing higher.",
  },
  {
    day: 4,
    title: "Namche Bazaar -> Tengboche",
    meta: "5.5 hrs - 9.2 km - +420m gain",
    text: "A stunning trek with views of Everest and Ama Dablam, passing through the famous Tengboche Monastery.",
    lodge: "Select Lodge for Tengboche",
  },
  {
    day: 5,
    title: "Tengboche -> Dingboche",
    meta: "6 hrs - 10.5 km - +550m gain",
    text: "Trekking through alpine landscapes and summer pastures to reach the high-altitude village of Dingboche.",
    lodge: "Select Lodge for Dingboche",
  },
];
